services:
  zookeeper:
    platform: linux/amd64
    image: confluentinc/cp-zookeeper:${CONFLUENT_PLATFORM_VERSION:-7.4.0}
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka

  sales:  # Kafka broker
    platform: linux/amd64
    image: confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION:-7.4.0}
    container_name: sales
    restart: unless-stopped
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://sales:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8087:8080"
    depends_on:
      - sales
    environment:
      KAFKA_CLUSTERS_0_NAME: sales
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: sales:9092
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - kafka

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - kafka


  backend:
    build:
      context: ./src
      dockerfile: backend/Dockerfile
    container_name: etl_service
    env_file:
      - .env
    depends_on:
      - postgres
      - sales
    entrypoint: ["sh", "-c", "sleep 10 && python main.py"]
    networks:
      - kafka

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: streamlit_app
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - postgres
      - backend
    entrypoint: ["sh", "-c", "sleep 10 && streamlit run app.py --server.port=8501 --server.address=0.0.0.0"]
    networks:
      - kafka

volumes:
  postgres_data:

networks:
  kafka:
    name: kafka
